export const CREATE_TICKET_REQUEST = 'CREATE_TICKET_REQUEST'
export const CREATE_TICKET_SUCCESS = 'CREATE_TICKET_SUCCESS'
export const CREATE_TICKET_FAIL = 'CREATE_TICKET_FAIL'
export const CREATE_TICKET_RESET = 'CREATE_TICKET_RESET'

export const GET_TICKETS_REQUEST = 'GET_TICKETS_REQUEST'
export const GET_TICKETS_SUCCESS = 'GET_TICKETS_SUCCESS'
export const GET_TICKETS_FAIL = 'GET_TICKETS_FAIL'
export const GET_TICKETS_RESET = 'GET_TICKETS_RESET'


export const GET_TICKET_DETAIL_REQUEST = 'GET_TICKET_REQUEST'
export const GET_TICKET_DETAIL_SUCCESS = 'GET_TICKET_SUCCESS'
export const GET_TICKET_DETAIL_FAIL = 'GET_TICKET_FAIL'


export const UPDATE_TICKET_REQUEST = 'UPDATE_TICKET_REQUEST'
export const UPDATE_TICKET_SUCCESS = 'UPDATE_TICKET_SUCCESS'
export const UPDATE_TICKET_FAIL = 'UPDATE_TICKET_FAIL'
export const UPDATE_TICKET_RESET = 'UPDATE_TICKET_RESET'