export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_RESET = "REGISTER_USER_RESET"
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL"

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL"
export const LOGIN_USER_RESET = "LOGIN_USER_RESET"

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const CREATE_USER_FAIL = "CREATE_USER_FAIL"
export const CREATE_USER_RESET = "CREATE_USER_RESET"

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"
export const LOAD_USER_FAIL = "LOAD_USER_FAIL"
export const LOAD_USER_RESET = "LOAD_USER_RESET"

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"
export const UPDATE_USER_RESET = "UPDATE_USER_RESET"

export const GET_EMPLOYEE_REQUEST = "GET_EMPLOYEE_REQUEST"
export const GET_EMPLOYEE_SUCCESS = "GET_EMPLOYEE_SUCCESS"
export const GET_EMPLOYEE_FAIL = "GET_EMPLOYEE_FAIL"
